easy_admin:
    entities:
        - App\Entity\Product
        - App\Entity\User
        - App\Entity\Stock
        - App\Entity\Store
    site_name: '<img style="width: 200px; height: auto;" src="https://images.g2crowd.com/uploads/product/image/social_landscape/social_landscape_1511988551/chatbox.png">'
    design:
        brand_color: 'red'
        
